### ISSUE TITLE
Update Documentation 

### ISSUE THREAD

**Issue by amanjiofficial** [amanjiofficial/tenjint-flask#1]
Documentation needs to be simplified more for the general use cases.

**Comment by chaitankris** [comment]
I can do that! please assign me!

**Comment by amanjiofficial** [comment]
Go ahead @chaitankris

**Comment by Ayush7-BIT** [comment]
Hey if possible assign this issue to me?

**Comment by amanjiofficial** [comment]
@Ayush7-BIT the issue is already assigned. You can raise new issues/ bug fixes / feature requests.
