### ISSUE TITLE
Code Refactor

### ISSUE THREAD

**Issue by amanjiofficial** [amanjiofficial/tenjint-flask#2]
the files in /api and files in /plugins need a good refactor and a better in code docs specially server.py

**Comment by dipanshug124** [comment]
Please assign this to me

**Comment by amanjiofficial** [comment]
Go ahead @dipanshug124

**Comment by pnidhi26** [comment]
I am interested in this project and having experience in Flask based API creation. Please assign some work to me.

**Comment by Ayush7-BIT** [comment]
Hey! if possible assign this issue to me...

**Comment by amanjiofficial** [comment]
@pnidhi26 @Ayush7-BIT the issue is already assigned. You can raise new issues/ bug fixes / feature requests.
